### ISSUE TITLE
Support HTTP websocket connections

### ISSUE THREAD

**Issue by kawaii** [nextcloud/jsxc.nextcloud#110]
I notice that this module currently supports HTTP BOSH connections to XMPP servers, BOSH is very quickly becoming superseded by websocket implementations (such as Prosody's [mod_websocket](https://prosody.im/doc/modules/mod_websocket)) and it'd be nice to know if the maintainers planned on updating the module to support this too?

**Comment by MarcelWaldvogel** [comment]
Apparently, the underlying `strophejs` library supports Websocket as well. So a pull request to [JSXC](https://github.com/jsxc/jsxc/) for the [upcoming 4.0 release](https://github.com/jsxc/jsxc/tree/refactoring) would be greatly appreciated.

See also jsxc/jsxc#500.

**Comment by sualko** [comment]
There is no websocket support yet, because you can't pause and continue such a connection on a page reload. Therefore this would be only useful on single page applications (or with our time-limited token in cases with only occasional reloads). As Marcel said, if you have time to work on this, this would be great, but it's currently not on our roadmap. Please feel free to reopen this, if you start to work on this.
