### ISSUE TITLE
Autoinvite new users to group MUC

### ISSUE THREAD

**Issue by poVoq** [nextcloud/jsxc.nextcloud#120]
Apparently there is no way in Ejabberd to auto invite new users to a MUC:
https://github.com/processone/ejabberd/issues/428

But it might be a cool feature for this App to set default MUC (per NC group?) that new users are automatically invited to?

**Comment by sualko** [comment]
This is not possible from a client side, because you need a way to protect that group/room and this is only possible with member only rooms, which needs an administrator. I like the idea, but it's out of the scope of this application. If you have an idea how this can be done easier, please reopen this issue.

**Comment by poVoq** [comment]
Hmm, I assumed this would be possible via shared roosters and the xcauth bridge? After all that can auto assign connections and groups without any issues.

But of course that would need to be exposed in the JSXC Nextcloud settings somehow.

**Comment by sualko** [comment]
> I assumed this would be possible via shared roosters and the xcauth bridge?

MUC rooms are not stored in the roster, they are stored in a bookmarks node. You also have to handle the room configuration and so on. I think the only way would be to use an admin bot, which is triggered to create rooms, add/remove users and so on. Maybe @MarcelWaldvogel has another idea.
