### ISSUE TITLE
Nextcloud integration no longer works

### ISSUE THREAD

**Issue by tigexplorer** [nextcloud/jsxc.nextcloud#170]
Maybe, since update to NC 20, I'm unable to use jsxc within Nextcloud Web.

LogIn in Nextcloud take a very long time, and after LogOn, the Chat-Area is empty.

With other Apps, like Conversations or Dino, XMPP via jsxc is running fine.

When I "LogIn without Chat" in Nextcloud Web, the login process is fast.

In the Nextcloud log I can only grep a few lines like this
`{"reqId":"ID","level":2,"time":"2021-04-28T14:23:08+00:00","remoteAddr":"IPv6","user":"--","app":"core","method":"POST","url":"/nextcloud/index.php/apps/ojsxc/settings","message":"Login failed: 'username' (Remote IP: 'v6')","userAgent":"Mozilla..."}`

**Comment by poVoq** [comment]
Seems to be still working here on NC21. Maybe something else went wrong with the update?

**Comment by sualko** [comment]
Sorry, that I didn't response. We just released a new version and maybe it fixes your issue as well.

**Comment by poVoq** [comment]
I get a "App with id ojsxc has invalid signature" when trying to install the new version (updating fails as well).

**Comment by sualko** [comment]
I'm so sorry for the inconvenience. I had to update the build files, because yarn reused a wrong cached package, and I didn't check the build afterwards. Therefore it will take some time until the new signature populates across the NC app store. Tomorrow I will release a new version, so everyone gets the new build.
