### ISSUE TITLE
Undefined index: loginForm

### ISSUE THREAD

**Issue by danger89** [nextcloud/jsxc.nextcloud#89]
Hi folks,

I'm getting an error message in my logging from JSXC.

```log
{"reqId":","level":3,"time":"2018-02-08T23:29:28+00:00","remoteAddr":"","user":"melroy","app":"PHP","method":"GET","url":"\/settings\/admin\/externalstorages","message":"Undefined index: loginForm at \/var\/www\/nextcloud\/html\/apps\/ojsxc\/settings\/personal.php#22","userAgent":"Mozilla\/5.0 (X11) Gecko\/20100101 Firefox\/58.0","version":"13.0.0.14"}
```

Regards, Melroy

**Comment by arinno** [comment]
Same here since upgrade to Nextcloud 13, this error keeps on coming to the log
 
In Internal Nextcloud log :
`Error | PHP | Undefined index: loginForm at /var/www/nextcloud/apps/ojsxc/settings/personal.php#22
`
I tried desinstalling app and reinstalling it without success, I don't see what it is affecting yet as I am still able to use the tchat.

**Comment by sualko** [comment]
This has been already fixed in b3ac678d3b02f022f8315ad8f7991c50c2365bdf

**Comment by Failure404** [comment]
I guess this needs to be fixed in "jsxc.nextcloud/lib/Settings/Personal.php" as well because I am still getting
"Undefined index: loginForm at \/var\/www\/vhosts\/xxx\/userapps\/ojsxc\/lib\/Settings\/Personal.php#34"

**Comment by AlexCloudDev** [comment]
I fixed it in "apps/ojsxc/lib/Settings/Personal.php" and "apps/ojsxc/Settings/Personal.php" but still getting the error 
`Undefined index: loginFormEnable at /var/www/html/apps/ojsxc/templates/settings/personal.php#14`

I'm at nextcloud 13.0.5
